nodeLinker: node-modules
httpTimeout: 500000
yarnPath: .yarn/releases/yarn-4.0.1.cjs

npmScopes:
  valleywood:
    npmAuthToken: "${GITHUB_TOKEN:-none}"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"